name = "browserslist-mcp"
main = "src/worker/index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
workers_dev = true

# Build configuration
[build]
command = ""

# Observability
[observability]
enabled = true

# Development configuration
[dev]
port = 8787
ip = "0.0.0.0"

# Environment variables (optional)
[vars]
# Add any environment variables here

# Production environment
[env.production]
name = "browserslist-mcp-production"
